name: bundle
on:
  push:
    branches:
      - master
  pull_request:
      - master
jobs:
  main:
    name: tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Verify bundle
      run: |
        make verify-bundle
